apiVersion: batch/v1
kind: CronJob
metadata:
  name: bio-cronjob
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      parallelism: 1
      template:
        spec:
          containers:
            - name: bio
              image: docker.io/mariomang/bio:1.0.3
              imagePullPolicy: Always
              env:
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: bio
                      key: token
          restartPolicy: OnFailure
