apiVersion: batch/v1
kind: CronJob
metadata:
  name: bio-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: bio
              image: docker.io/mariomang/bio:test
              imagePullPolicy: IfNotPresent
              env:
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: bio
                      key: token
          restartPolicy: OnFailure
